sudo: required
dist: trusty
language: node_js
node_js:
  - 8
cache:
  - pip
  - yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3 
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  - TEST_DIR=./
script: cd $TEST_DIR && yarn install && npm test
