sudo: required
dist: trusty
language: node_js
node_js:
  - 10 
cache:
  - pip
  - yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3 
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  - TEST_DIR=./
  - TEST_DIR=packages/i13n-client
script: cd $TEST_DIR && yarn --ignore-engines && npm test
