
version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      test-dir:
        type: string
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: "13"
          install-yarn: true
      - run:
          name: Run YARN tests
          command: "yarn --ignore-engines && cd << parameters.test-dir >> && yarn --ignore-engines && npm test"


workflows:
  run-node-tests:
    jobs:
    - test:
        matrix:
          name: test-<< matrix.test-dir >>
          parameters:
            test-dir: ["./", "packages/i13n-client"]
