jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

dependencies:
  pre:
  - curl -fsSL https://git.io/v2Ifn | bash

version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  run-node-tests:
    jobs:
      - test
